### PR TITLE
Fix power_parameters JSON parsing error

### PR DESCRIPTION
**Pull request by juan-vg**
Fixes the _CallError_ when creating a machine with the `power_parameters` dict parameter.

```
client.bones.CallError: POST http://<maas_server>:5240/MAAS/api/2.0/machines/ -> HTTP 400 Bad Request (Failed to parse JSON power_parameters)
```

### CODE REVIEW

**Comment by blakerouse** [comment]
Looks like a good start, is it possible that you could add a unit test to cover the change?

Also it is required as a contributor to a Canonical project that you create a launchpad.net account and sign the Canonical Contributors agreement.

https://www.ubuntu.com/legal/contributors

Once your have completed this or if you already have, please provide me your launchpad-id and I will verify.

**Comment by juan-vg** [comment]
@blakerouse 

Hey! I'm fixing the testing part in order to cover that!

My launchpad Id is `juan.vela`. I've signed the agreement

**Comment by blakerouse** [comment]
Have you tested this change with an actual MAAS? What version of the MAAS are you testing against?

**Comment by juan-vg** [comment]
@blakerouse 

Yes, I've tested it. It's my fault for not saying which is my environment

Pyhton 3.6.7
python-libmaas==0.6.1
MAAS 2.5.0-7442-gdf68e30a5-0ubuntu1~18.04.1

**Comment by blakerouse** [comment]
Have you validated that the reading of machine parameters is also not affected once set?

If this is ready to merge please remove the WIP: prefix from the title.

**Comment by juan-vg** [comment]
@blakerouse 
Yes! I've validated it.

### Without the fix
```
In [8]: machine = client.machines.create( 
   ...:     "amd64", 
   ...:     [""], 
   ...:     "ipmi", 
   ...:     { 
   ...:         'power_pass': 'abcdefghijk', 
   ...:         'power_user': 'maas', 
   ...:         'power_driver': 'LAN_2_0', 
   ...:         'power_address': '10.0.0.3', 
   ...:         'power_boot_type': 'efi' 
   ...:     } 
   ...: )
[...]
CallError: POST http://10.0.0.1:5240/MAAS/api/2.0/machines/ -> HTTP 400 Bad Request (Failed to parse JSON power_parameters)
```

### With the fix
```
In [3]: machine = client.machines.create(  
   ...:     "amd64",  
   ...:     [""],  
   ...:     "ipmi",  
   ...:     {  
   ...:         'power_pass': 'abcdefghijk',  
   ...:         'power_user': 'maas',  
   ...:         'power_driver': 'LAN_2_0',  
   ...:         'power_address': '10.0.0.3',  
   ...:         'power_boot_type': 'efi'  
   ...:     }  
   ...: )                                                                                                                                                                                                          

In [4]: machine                                                                                                                                                                                                    
Out[4]: <Machine hostname='holy-skunk' system_id='bckaek'>

In [5]: machine.get_power_parameters()                                                                                                                                                                             
Out[5]: 
{'power_pass': 'abcdefghijk',
 'power_user': 'maas',
 'power_driver': 'LAN_2_0',
 'power_address': '10.0.0.3',
 'power_boot_type': 'efi',
 'mac_address': ''}
```

**Pull request merged**
