### PR TITLE
'Facade' object has no attribute 'read'

### PR DESCRIPTION
**Pull request by martinstrycek**
It should be `list()` instead of `read()` and `machine` instead of `node`

### CODE REVIEW

**Comment by brendan-donegan** [comment]
Good spot, thanks. You can merge this once the checks pass.

**Comment by blakerouse** [comment]
@martinstrycek Thank you so much for your contribution. Our legal department requires you to sign the Canonical contributor agreement before we can merge this pull request.

Would you be able to sign the agreement? https://www.ubuntu.com/legal/contributors/submit

If so please let me know once you have signed it.

**Comment by martinstrycek** [comment]
done

**Comment by blakerouse** [comment]
Thank you for signing the agreement and for the contribution. Looking forward to merging your future contributions!

**Pull request merged**
